from enemy import *

blub = blub()
bblub = bigblub()
spooder = spooder()
snek = snek()
skull = skullitor()
mother = mother()
team = [blub, bblub, spooder, snek, skull, mother]

for x in team:
    x.take_turn()
    print(x.name)
    print(x.msg)
    print(x.dmg)
    print()
for x in team:
    x.take_turn()
    print(x.name)
    print(x.msg)
    print(x.dmg)
    print()
for x in team:
    x.take_turn()
    print(x.name)
    print(x.msg)
    print(x.dmg)
    print()
for x in team:
    x.take_turn()
    print(x.name)
    print(x.msg)
    print(x.dmg)
    print()

skull.take_turn()
print(skull.msg)
print(skull.dmg)
skull.take_turn()
print(skull.msg)
print(skull.dmg)
skull.take_turn()
print(skull.msg)
print(skull.dmg)
skull.take_turn()
print(skull.msg)
print(skull.dmg)
skull.take_turn()
print(skull.msg)
print(skull.dmg)
skull.take_turn()
print(skull.msg)
print(skull.dmg)
skull.take_turn()
print(skull.msg)
print(skull.dmg)
skull.take_turn()
print(skull.msg)
print(skull.dmg)

